### PR TITLE
Support choosing the patch size

### PR DESCRIPTION
**Pull request by sygi**
Use the dummy slider to allow choosing 512 or 1024 square patch size.

Note: as of now, changing the size will clean up the canvas.

### CODE REVIEW

**Comment by TKoestlerx** [comment]
I had never dared to set the window size that high. However, the results are better than expected. (Even if the batch size suffers).
I don't think we need to reset the canvas when the size changes. It should be enough to reset the existing markers (and patches) and make a redrawCanvas call?
And changing the step size from 512 to 64 should support all "square" combinations.

Of course it would be even cooler to get the size directly from the gradio sliders.

gradioApp().getElementById('img2img_width').querySelector('input[type="range"]').value

But then we would have to set observers to those values or check the set size on each select click and adjust if necessary....
And maybe use the "dummy" slider to define the maximum outpaint (currently 400) with the bigger square sizes that would really make sense.


And there I thought the little tool was complete;)

**Comment by sygi** [comment]
I made some simple changes. I didn't do the "don't reset the canvas on size change", as this will require a bit work: I may be able to do this, but probably only in a couple of days.

**Comment by sygi** [comment]
I think I actually got the canvas not resetting to work in https://github.com/sygi/sdAlphaCanvas/tree/dont-reset2. Let's still merge these two one by one, though.

**Comment by TKoestlerx** [comment]
I have made the whole size selection dynamic.
So it can be any values allowed in the gradio width/height selection.

The check is only done in the cancas onclick function. If the width/height selection differs from the width/height of the gradio interface it will reset itself (and all markings.).
But the canvas itself will not reset and keep its content.

I also made the max Outdraw Range (was 400px) dynamic and added a basic snap grid.

**Comment by sygi** [comment]
Nice, it looks like your recent change contains all that was done in my branches, so I'm closing this PR.

By the way, I was searching the gradio docs on how to read the value of another slider, but it doesn't seem to be easy from another module. I asked [this question](https://discuss.huggingface.co/t/update-gr-slider-from-the-html-dom/25591) in the gradio forum but didn't get an answer.

**Comment by TKoestlerx** [comment]
I think as long as they are named elements like the generell width/height elements i had no problems obtaining their values with just checking their scope for the element im looking for like:
"
parseInt(gradioApp().getElementById('img2img_width').querySelector('input[type="range"]').value);
"
But most of the other controls are not as easy to locate from the js side.

And thanks for starting the size discussion. I didnt experiment with other sizes besides 512x512 before. But it can be really useful to just increase the windows-size sometimes.

**Pull request closed without merging**
